9 sprint homework
BLADBORNE/java-filmorate pull request #5
Opened 2024-03-03 12:31 UTC by BLADBORNE

Made processing of endpoints when accessing /users and /films - methods GET, POST, PUT

2024-03-03 20:21 UTC, andrew-larkin requested changes
Привет! Хороший старт!  Несколько небольших правок, а также надо бы тесты написать, а то их вообще нет.

2024-03-03 20:21 UTC, andrew-larkin commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
повторяющиеся проверки лучше вынести в отдельный метод

2024-03-03 20:21 UTC, andrew-larkin commented on src/main/resources/application.properties
> +#logging.level.org.springframework.web.servlet.DispatcherServlet=debug
закомментированный код удаляем

2024-03-04 16:15 UTC, BLADBORNE commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (user.getBirthday().isAfter(LocalDate.now())) {
Исправил DRY принцип)

2024-03-04 16:17 UTC, BLADBORNE commented on src/main/resources/application.properties
> +#logging.level.org.springframework.web.servlet.DispatcherServlet=debug
@andrew-larkin, удалил все ненужные импорты!

2024-03-05 20:19 UTC, merged